### ISSUE TITLE
More geo-filters

### ISSUE THREAD

**Issue by oskarrough** [internet4000/lpepfinder#1]
Feature request to be able to search all shops in Europe at once.

**Comment by hugurp** [comment]
Good idea, will look into it. Google CSE does not really allow to automatically asign tags to other tags, but will try manually!

So the idea would be to group countries also by continent?
- Americas? North-america?
- Europe
- Asia? Est-asia?

Not sure, maybe we start with Europe and see what are the needs?

**Comment by oskarrough** [comment]
Yes. Doing it manually and just for Europe to start with sounds good to me.

**Comment by hugurp** [comment]
Thanks for the suggestion, this is done: https://lpepfinder.com/#gsc.tab=0&gsc.q=tomorrow's%20people&gsc.ref=more%3Aeurope

Maybe a bit polemic, but I added UK in Europe, using, not the politic, but geographic Europe.
peace
