### ISSUE TITLE
button to add boolean search removing "out of stock" items?

### ISSUE THREAD

**Issue by hugurp** [internet4000/lpepfinder#3]
Maybe a little button in the UI to suffix to the search query a `<user-search> NOT "out of stock"`.

Not sure it works 100%, but can be nice to filter out some items in some situations.

**Comment by oskarrough** [comment]
I think that's a fair solution. It'll be better than nothing and easy to do!

**Comment by hugurp** [comment]
gave it a try here https://github.com/internet4000/lpepfinder/commit/1e0ede20565dc02e6358d58b172f91403574a6a3#diff-eacf331f0ffc35d4b482f1d15a887d3bR93
